version: 2.1

jobs:
  test:
    description: Runs unit tests and instrumented tests on the Android Common
    docker:
      - image: circleci/android:2020.10
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Download and Install SDK Packages
          command: sdkmanager "system-images;android-29;google_apis;x86" "platform-tools" "platforms;android-29" "emulator" --sdk_root=/usr/local/android-sdk
      - run:
          name: Create and Start Emulator
          command: |
            echo "no" | avdmanager --verbose create avd --force --name test --package "system-images;android-29;google_apis;x86" --abi google_apis/x86
            emulator -avd test -no-window -no-audio -no-snapshot -gpu swiftshader_indirect &
            circle-android wait-for-boot
      - run:
          name: Wait for Emulator to Start
          command: adb wait-for-device
      - run:
          name: Install APKs and Run Tests
          command: ./gradlew installSnapshotDebug && ./gradlew testSnapshotDebugUnitTest && ./gradlew grantPermissionForODKXApp connectedSnapshotDebugAndroidTest
      - store_artifacts:
          name: Store Test Results
          path: services_app/build/outputs/androidTest-results
      - store_artifacts:
          name: Store Test Reports
          path: services_app/build/reports

workflows:
  build-test-workflow:
    jobs:
      - test
