version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  find-jdk-path:
    docker:
      - image: cimg/android:2024.04
    steps:
      - run:
          name: List JDKs
          command: ls -l /usr/lib/jvm

workflows:
  find-jdk-path-workflow:
    jobs:
      - find-jdk-path