version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  test:
    description: Runs unit tests and instrumented tests on the Android Common
    executor:
      name: android/default
      tag: 2024.01.1

    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/setup-emulator:
          api-level: 29
          emulator-type: full
      - android/wait-for-emulator:
          timeout-sec: 180
      - run:
          name: Install APKs and Run Tests
          command: ./gradlew installSnapshotDebug && ./gradlew testSnapshotDebugUnitTest && ./gradlew grantPermissionForODKXApp connectedSnapshotDebugAndroidTest
      - store_artifacts:
          name: Store Test Results
          path: services_app/build/outputs/androidTest-results
      - store_artifacts:
          name: Store Test Reports
          path: services_app/build/reports

  build:
    docker:
      - image: cimg/android:2024.01

    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build Services
          command: ./gradlew assembleSnapshotDebug
      - store_artifacts:
          name: Store Build Artifacts
          path: services_app/build/outputs/apk
      - persist_to_workspace:
          root: .
          paths:
            - services_app/build/outputs/apk

workflows:
  build-test-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
